import React from 'react'
import { useParams } from 'react-router-dom';
import gokarna from "../../Images/gokarna.jpg"
import "./blogs.css"
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import Navbar2 from '../../Components/Nav/Navbar/Navbar2';
import Footer from '../../Components/Nav/Footer/Footer';
const Blogs = () => {

  const {id}  = useParams();
  console.log("param",id)
  const jsonData = [
    { id: 1, name: 'Enma ',img:gokarna , description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est', 
  description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
  description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis."},
    { id: 2, name: 'Gary',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 3, name: 'Micheal',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 4, name: 'Stacey',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 5, name: 'Bill',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 6, name: 'Ethan',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 7, name: 'Rose',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 8, name: 'Jerry',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 9, name: 'Johnathan',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 10, name: 'Elliot',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 11, name: 'Mary',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 12, name: 'Gary',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 13, name: 'Benedict',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 14, name: 'Moses',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 15, name: 'Natasha',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 16, name: 'Joshua',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 17, name: 'Celia',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 18, name: 'Isaac',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 19, name: 'Alexander',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 20, name: 'Hannah',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 21, name: 'Gabriel',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 22, name: 'Abigail',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 23, name: 'Daniel',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 24, name: 'James',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 25, name: 'Samuel',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 26, name: 'Benjamin',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 27, name: 'Sarah',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 28, name: 'Sarah',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 29, name: 'Isabella',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 30, name: 'Christopher',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 31, name: 'Christopher',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 32, name: 'Emma',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 33, name: 'Andrew',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 34, name: 'Lydia',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 35, name: 'David',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 36, name: 'Esther',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 37, name: 'Esther',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 38, name: 'Solomon',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 39, name: 'Rachel',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 40, name: 'Philip',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 41, name: 'Charles',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 42, name: 'Raphael',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 43, name: 'Theodore',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 44, name: 'Anthony',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 45, name: 'Christian',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 46, name: 'Grace',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 47, name: 'Lydia',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 48, name: 'Elizabeth',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 49, name: 'Ruth',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 50, name: 'Elijah',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 51, name: 'Olivia',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 52, name: 'Sophia',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    { id: 53, name: 'Timothy',img: gokarna, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor sagittis sem. Aenean vel euismod sapien, id sagittis lorem. Pellentesque cursus orci in iaculis tempus. Vivamus quis odio non nunc tempus fermentum eget non ipsum. Maecenas mollis dolor quis velit sollicitudin, in accumsan urna egestas. In hac habitasse platea dictumst. Ut eros justo, pretium vel leo et, sodales posuere mi. Nunc sit amet dui ipsum. Nulla aliquet iaculis ex, a sagittis elit finibus ac. Aliquam commodo, tortor eget accumsan vulputate, lacus est facilisis mi, quis molestie ante augue quis est',
    description1: "Etiam sollicitudin mattis eros, sit amet congue eros euismod id. Aenean at dapibus quam. Integer feugiat iaculis ornare. Nunc bibendum nisi non lobortis bibendum. Praesent et cursus lorem, sed luctus neque. Nam posuere eu est sed egestas. In dignissim pharetra massa non fringilla. Maecenas dignissim egestas sollicitudin. Nunc ac venenatis mi. Nullam vulputate porta vestibulum.",
    description2: "Integer sed metus et orci pharetra euismod vitae at est. Phasellus a fringilla elit, at convallis nisl. Curabitur bibendum ipsum mi, ut accumsan dolor congue eget. Mauris felis augue, sodales id ipsum non, rhoncus dictum sapien. Sed eget tellus ultrices, venenatis metus vel, commodo ligula. Nam a vehicula lectus. In ac leo quis neque ultricies varius non sit amet purus. Pellentesque rutrum tincidunt nisi, vel fringilla diam fermentum quis." },
    






  ];
  const item = jsonData.find(item => item.id == id );
  return (
    <div className='blogpost9'>
        <Navbar2 />
        {item ? (
          <div >
        <div className='blog-dummy9'></div>
    
     <div className='blog-head9'>
     <Carousel  showThumbs={false}>
      <div>
        <img src={gokarna} alt="Image 1" />
 
      </div>
      <div>
        <img src={gokarna} alt="Image 2" />
      </div>
      <div>
        <img src={gokarna} alt="Image 3" />
      </div>
    </Carousel>

        
        
        </div> 
         <div className='blog-body'>
        {/* <div className='img'></div> */}
        <div className='blog-title'>
        {item.name}</div>
      <div className='blog-body-para'>{item.description}
</div>
    <div className='blog-body-para1'>{item.description1}</div>
    <div className='blog-body-para1'>{item.description2}
</div>
    




        </div>
        </div>
        ) : (
          <p>Data not found</p>
       )}
<Footer />
    </div>

 )
}

export default Blogs
